#!/bin/env ruby

require 'debugger'
require 'rubygems'
require 'thor'
require 'zip'      # Rubyzip
require 'RMagick'
require_relative './kml'


class MapExtractor < Thor
  desc "map file", "Converts the kml file to a flat map"
  def map in_file
    out_file = in_file.gsub(/\.[^.]*?$/, '.png')

    kml = Kml.new(in_file)

    puts "Converting #{in_file} to #{out_file}"

    kml.to_image.write(out_file)
  end
end

MapExtractor.start
