#!/bin/env ruby

require 'debugger'
require 'rubygems'
require 'thor'
require 'zip'      # Rubyzip
require 'RMagick'
require_relative './kml'


class MapExtractor < Thor
  desc "map file", "Converts the kml file to a flat map"
  def map in_file
    out_file = File.basename(in_file.gsub(/\.[^.]*?$/, '.png'))

    map = Dir.chdir(File.dirname(in_file)) do

      kml = Kml.new(File.basename(in_file))
      puts "Converting #{in_file} to #{out_file}"

      kml.to_map
    end

    puts map.info
    map.write(out_file)
  end
end

MapExtractor.start
